---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: collect-worker-node-pod-info
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.4.0
    systemd:
      units:
        - name: node-pod-info.service
          enabled: true
          contents: |
            [Unit]
            Description=Node Pod Info Service
            After=network.target

            [Service]
            ExecStart=/usr/local/bin/node-pod-info.sh
            Restart=always
            RestartSec=10

            [Install]
            WantedBy=multi-user.target
    storage:
      files:
        - path: /usr/local/bin/node-pod-info.sh
          mode: 0755
          overwrite: true
          contents:
            source: data:text/plain;charset=utf-8;base64,IyEvYmluL3NoCgojIyMjIyMjIyMjIyMjIyMjCiNEZXNjcmlwdGlvbjoKI1RoaXMgc2NyaXB0IGlzIHRvIHRyb3VibGVzaG9vdCBodHRwczovL2lzc3Vlcy5yZWRoYXQuY29tL2Jyb3dzZS9PQ1BCVUdTLTM1MDcwIHRvIGdhdGhlciB0aGUgcG9kcyBjb3VudCBhdHRhY2hlZAojdG8gY2x1c3RlciBkZWZhdWx0IG5ldHdvcmsgYW5kIGFjdGl2ZWx5IHJ1bm5pbmcgaW4gYSB3b3JrZXIgbm9kZSBmcm9tIHRoZSBjb250cm9sIHBsYW5lLCBhcyB3ZWxsIGFzIHRoZSBwb2RzIElQCiNjb3VudCBpbiB0aGUgU0ROIENOSSBkaXJlY3RvcnkgaW4gYSB3b3JrZXIgbm9kZS4KIwojRXhhbXBsZToKI0xldCdzIHNheSBpZiB0aGUgY2lkciBhc3NpZ25lZCBmb3IgYSBub2RlIGlzIC8yNCBhbmQgd2Ugc2VlIHBvZHMgSVAgY291bnQgbGlzdGVkIGluIFNETiBkaXJlY3RvcnkgaXMgMjU0KHRoaXMgaXMKI3RoZSBtYXggcG9zc2libGUgSVAgY291bnQgd2UgY2FuIHNlZSBmb3IgLzI0KSBhbmQgaWYgdGhlIHBvZHMgY291bnQgYXR0Y2hlZCB0byBjbHVzdGVyIGRlZmF1bHQgbmV0d29yayBpcyBsZXNzCiN0aGFuIHRvIGl0LFRoZW4gd2UgY2FuIHNheSBTRE4gQ05JIGRpcmVjdG9yeSBoYXZlIHNvbWUgc3RhbGUgSVBTIGFuZCBwb3NzaWJseSB0aGV5IGZhaWxlZCB0byBnZXQgcmVtb3ZlZCBmcm9tIHRoCiNlIGRpcmVjdG9yeSB3aGVuIHRoZSBjb3JyZXNwb2RpbmcgcG9kcyBoYXZlIHJlbW92ZWQuVGhpcyB3YXkgd2UgY2FuIHByb3ZlIHRoYXQgU0ROIENOSSBoYXMgc29tZSB1bnVzZWQgSVAgZmlsZXMKI2FuZCB0aGF0IGlzIGNhdXNpbmcgdG8gbm90IGZpbmRpbmcgYW4gSVAgdG8gYWxsb2NhdGUgZnJvbSBhbiBhc3NpZ25lZCBDSURSIHRvIGEgd29ya2VyIG5vZGUgd2hlbiBhIG5ldyBwb2QgaXMgY3IKI2VhdGVkIGluIGl0LgojIyMjIyMjIyMjIyMjIyMjIwoKIyBGdW5jdGlvbiB0byBoYW5kbGUgY2xlYW51cCBvbiB0ZXJtaW5hdGlvbgpjbGVhbnVwKCkgewoJZWNobyAiRVJST1I6IFJlY2VpdmVkIFNJR1RFUk0uIEV4aXRpbmcgZ3JhY2VmdWxseSBhdCAkKGRhdGUgJyslWS0lbS0lZCAlSDolTTolUycpLiIKCWV4aXQgMAp9CgojIFRyYXAgU0lHVEVSTSBhbmQgY2FsbCB0aGUgY2xlYW51cCBmdW5jdGlvbgp0cmFwIGNsZWFudXAgVEVSTQoKd2hpbGUgOjsgZG8KCSNDb3VudGluZyB0aGUgbGlzdCBvZiBpcHY0IGZpbGVzIGNyZWF0ZWQgaW4gJENOSV9ORVRXT1JLX0RJUgoJQ05JX05FVFdPUktfRElSPSIvdmFyL2xpYi9jbmkvbmV0d29ya3Mvb3BlbnNoaWZ0LXNkbiIKCUFMTE9DQVRFRF9JUFM9JChmaW5kICRDTklfTkVUV09SS19ESVIgLXR5cGUgZiAtcmVnZXh0eXBlIHBvc2l4LWV4dGVuZGVkIC1yZWdleCAnLiovKFswLTldezEsM31cLil7M31bMC05XXsxLDN9JCcgfCB3YyAtbCkKCgkjQ291bnRpbmcgdGhlIHBvZHMgaW4gYSB3b3JrZXIgbm9kZSB0aGF0IGFyZSBhdHRhY2hlZCB0byB0aGUgY2x1c3RlcidzIGRlZmF1bHQgbmV0d29yaywgc3RhdHVzIGlzIHJ1bm5pbmcKCSNhbmQgaGF2ZSBhbiBJUCBhZGRyZXNzIGFzc2lnbmVkIHRvIHRoZW0KCVBPRF9DT1VOVD0kKG9jIC0ta3ViZWNvbmZpZz0vdmFyL2xpYi9rdWJlbGV0L2t1YmVjb25maWcgZ2V0IHBvZHMgLUEgXAoJCS0tZmllbGQtc2VsZWN0b3Igc3BlYy5ub2RlTmFtZT0iJChob3N0bmFtZSkiLHN0YXR1cy5wb2RJUCE9bnVsbCxzdGF0dXMucGhhc2U9IlJ1bm5pbmciIFwKCQktbyBqc29uIHwganEgJ1suaXRlbXNbXSB8IHNlbGVjdCgubWV0YWRhdGEuYW5ub3RhdGlvbnNbIms4cy52MS5jbmkuY25jZi5pby9uZXR3b3JrLXN0YXR1cyJdIHwgZnJvbWpzb24/IHwgYW55KC5kZWZhdWx0KSldIHwgbGVuZ3RoJykKCglpZiBbICIkUE9EX0NPVU5UIiAtbHQgIiRBTExPQ0FURURfSVBTIiBdOyB0aGVuCgkJZWNobyAiRVJST1I6ICQoZGF0ZSAnKyVZLSVtLSVkICVIOiVNOiVTJykgLSBQT0QgQ09VTlQgaXMgbGVzcyB0aGFuIHRoZSBQT0QgSVBzIEFsbG9jYXRlZC4gQSBmZXcgc3RhbGUgSVB2NCBmaWxlcyBjb3VsZCBiZSBleGlzdGluZyBpbiB0aGUgJChDTklfTkVUV09SS19ESVIpIgoJZWxpZiBbICIkUE9EX0NPVU5UIiAtZ3QgIiRBTExPQ0FURURfSVBTIiBdOyB0aGVuCgkJZWNobyAiRVJST1I6ICQoZGF0ZSAnKyVZLSVtLSVkICVIOiVNOiVTJykgLSBQT0QgQ09VTlQgaXMgZ3JlYXRlciB0aGFuIHRoZSBQT0QgSVBzIEFsbG9jYXRlZCIKCWVsc2UKCQllY2hvICJJTkZPOiAkKGRhdGUgJyslWS0lbS0lZCAlSDolTTolUycpIC0gUE9EIGFuZCBQT0QgSVAgQ291bnQgYXJlIHNhbWUiCglmaQoJZWNobyAiSU5GTzogJChkYXRlICcrJVktJW0tJWQgJUg6JU06JVMnKSAtIFBPRCBDT1VOVDogJHtQT0RfQ09VTlR9IGFuZCBQT0RJUHMgQ09VTlQ6ICR7QUxMT0NBVEVEX0lQU30iCglzbGVlcCAzNjAwCmRvbmUK
